version: "3.9"

services:
  # ----------- Databases -----------
  product_db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: products
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"   # local access (optional)
    volumes:
      - product_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d products"]
      interval: 5s
      timeout: 5s
      retries: 10

  order_db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: orders
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - order_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d orders"]
      interval: 5s
      timeout: 5s
      retries: 10

  customer_db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: customers
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - customer_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d customers"]
      interval: 5s
      timeout: 5s
      retries: 10

  # ----------- Services -----------
  product_service:
    build: ./backend/product_service
    environment:
      DATABASE_URL: postgresql://postgres:postgres@product_db:5432/products
    depends_on:
      product_db:
        condition: service_healthy
    ports:
      - "8001:8000"

  order_service:
    build: ./backend/order_service
    environment:
      DATABASE_URL: postgresql://postgres:postgres@order_db:5432/orders
    depends_on:
      order_db:
        condition: service_healthy
    ports:
      - "8002:8000"

  customer_service:
    build: ./backend/customer_service
    environment:
      DATABASE_URL: postgresql://postgres:postgres@customer_db:5432/customers
    depends_on:
      customer_db:
        condition: service_healthy
    ports:
      - "8003:8000"

volumes:
  product_db_data:
  order_db_data:
  customer_db_data:
