apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deploy
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: PLACEHOLDER_REG/order_service:latest
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: order-svc
  namespace: prod
spec:
  selector:
    app: order
  ports:
    - port: 80
      targetPort: 8000
  type: ClusterIP
