apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deploy
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels: { app: product }
  template:
    metadata:
      labels: { app: product }
    spec:
      containers:
        - name: product
          image: PLACEHOLDER_REG/product_service:latest
          ports: [{ containerPort: 8000 }]
---
apiVersion: v1
kind: Service
metadata:
  name: product-svc
  namespace: prod
spec:
  selector: { app: product }
  ports: [{ port: 80, targetPort: 8000 }]
  type: ClusterIP
