apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deploy
  namespace: prod
spec:
  replicas: 1
  selector: { matchLabels: { app: frontend } }
  template:
    metadata: { labels: { app: frontend } }
    spec:
      containers:
        - name: frontend
          image: YOUR_ACR_NAME.azurecr.io/frontend:latest
          ports: [{ containerPort: 80 }]
          readinessProbe: { httpGet: { path: /, port: 80 } }
          livenessProbe:  { httpGet: { path: /, port: 80 } }
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: prod
spec:
  selector: { app: frontend }
  ports: [{ name: http, port: 80, targetPort: 80 }]
  type: LoadBalancer