apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-deploy
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer
  template:
    metadata:
      labels:
        app: customer
    spec:
      containers:
        - name: customer
          image: PLACEHOLDER_REG/customer_service:latest
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: customer-svc
  namespace: prod
spec:
  selector:
    app: customer
  ports:
    - port: 80
      targetPort: 8000
  type: ClusterIP
